---
version: '3'

tasks:
  default:
    cmds:
      - task --list

  lint:
    desc: lint files
    cmds:
      - yamllint -c .github/lint/.yamllint.yml .
      - mdl --config .github/lint/.mdlrc --style .github/lint/.mdl.rb .

  pretty:
    desc: fix errors
    cmds:
      - prettier --config ".github/lint/.prettierrc.yaml" --write --list-different --ignore-unknown .

  pre-commit:
    desc: run pre-commit verbosely
    cmds:
      - pre-commit run --all-files --show-diff-on-failure
